@DNS_HOST = http://ec2-3-35-138-197.ap-northeast-2.compute.amazonaws.com:8080

### Save Heart Rate
POST {{DNS_HOST}}/api/v1/heart-rate
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "heartRate": 80
}
