

jwt:
  secret: Tm92YUhvbWVQYWdlc2FkZmFzZGZhc2RmYXNkZnNhZGY=
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/smart_worker
    username: root
    password: sj991209
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
  data:
    mongodb:
      auto-index-creation: true
      host: localhost
      port: 27018

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
  endpoint:
    health:
      show-details: never

# SpringDoc and Swagger UI Configuration
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    display-request-duration: true
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
  show-actuator: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  writer-with-default-pretty-printer: true

sms:
  from: 01044745825
  apiKey: NCSA942P5OFNFMQT
  apiSecret: O2HJXMNM6IO4VOUBC3N7XPIFZLB8G6MR
  serviceDomain: https://api.coolsms.co.kr
