version: '3.7'

services:
  api-module:
    image: bsj1209/smart-worker:dev
    container_name: smart-worker-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - ${GLOBAL_NETWORK:-api-module}

